version: '2'

volumes:
  volume_mysql:
    driver: local
  volume_redis:
    driver: local

networks:
  local-network:
    driver: bridge

services:
  mysql_server:
    image: mysql:5.7
    volumes:
        - volume_mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: passwd
        MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - local-network

  redis_server:
    image: redis:latest
    volumes:
      - volume_redis:/data
    networks:
      - local-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
        - ./www:/www
    networks:
      - local-network

  phpfpm:
    image: php7fpm:latest
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: secret_token
    volumes:
        - ./www:/www
    working_dir: /www
    tty: true
    stdin_open: true
    networks:
      - local-network