version: '2'

volumes:
  volume_mysql:
    driver: local
  volume_redis:
    driver: local
  volume_composer_cache:
    driver: local

networks:
  local-network:
    driver: bridge

services:
  mysql_server:
    image: mysql:5.7
    volumes:
        - volume_mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: passwd
        MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - local-network

  redis_server:
    image: redis:alpine
    volumes:
      - volume_redis:/data
    networks:
      - local-network

  nginx:
    image: phpocker_nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/vhosts.conf:/etc/nginx/conf.d/vhosts.conf
      - ./public_html:/www
    networks:
      - local-network

  phpfpm:
    image: phpocker_php7fpm:latest
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: secret_token
    volumes:
        - ./public_html:/www
        - volume_composer_cache:/root/.composer/cache
    working_dir: /www
    networks:
      - local-network
